const express = require("express");
require("dotenv").config();

const { createClient } = require("@supabase/supabase-js");
const crypto = require("crypto");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 3000;

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);

const ADMIN_PIN = process.env.ADMIN_PIN || "civicconnectrishu9031@";

app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

// =========================
// ADMIN SESSIONS
// =========================

const sessions = new Map();

function auth(req, res, next) {
  const token = (req.headers.authorization || "").replace("Bearer ", "");

  if (!token || !sessions.has(token)) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  next();
}

// =========================
// CREATE COMPLAINT
// =========================

app.post("/api/complaints", async (req, res) => {
  try {
    const name = String(req.body.name || "").trim();
    const phone = String(req.body.phone || req.body.mobile || "").trim();
    const category = String(
      req.body.category || req.body.type || ""
    ).trim();

    const location = String(
  req.body.location ||
  req.body.area ||
  req.body.address ||
  ""
).trim();

    const description = String(
      req.body.description || req.body.descreption || ""
    ).trim();

    const latitude =
      req.body.latitude !== undefined &&
      req.body.latitude !== null &&
      req.body.latitude !== ""
        ? Number(req.body.latitude)
        : null;

    const longitude =
      req.body.longitude !== undefined &&
      req.body.longitude !== null &&
      req.body.longitude !== ""
        ? Number(req.body.longitude)
        : null;

    // Validation
    if (
      !name ||
      !/^\d{10}$/.test(phone) ||
      !category ||
      !location ||
      !description ||
      description.length < 10
    ) {
      return res.status(400).json({
        error: "Invalid complaint data"
      });
    }

    // Insert complaint.
    // complaint_id is generated by Supabase/database.
    const { data, error } = await supabase
      .from("complaints")
      .insert({
        name,
        phone,
        category,
        description,
        location,
        latitude:
          Number.isFinite(latitude) ? latitude : null,
        longitude:
          Number.isFinite(longitude) ? longitude : null,
        status: "Submitted"
      })
      .select("complaint_id,created_at")
      .single();

    if (error) {
      console.error(
        "Complaint insert failed:",
        error.message
      );

      return res.status(500).json({
        error: "Could not save complaint"
      });
    }

    return res.json({
      id: data.complaint_id,
      created: data.created_at || null
    });

  } catch (err) {
    console.error("Complaint API error:", err);

    return res.status(500).json({
      error: "Server error"
    });
  }
});

// =========================
// TRACK COMPLAINT
// =========================

app.get("/api/complaints/:id", async (req, res) => {
  try {
    const complaintId = String(req.params.id || "")
      .trim()
      .toUpperCase();

    if (!complaintId) {
      return res.status(400).json({
        error: "Complaint ID required"
      });
    }

    const { data, error } = await supabase
      .from("complaints")
      .select(
        "complaint_id,name,phone,category,description,location,latitude,longitude,status,assigned_to,created_at"
      )
      .eq("complaint_id", complaintId)
      .maybeSingle();

    if (error) {
      console.error(
        "Tracking error:",
        error.message
      );

      return res.status(500).json({
        error: "Could not fetch complaint"
      });
    }

    if (!data) {
      return res.status(404).json({
        error: "Complaint not found"
      });
    }

    return res.json({
      id: data.complaint_id,
      name: data.name,
      phone: data.phone,
      category: data.category,
      description: data.description,
      area: data.location,
      location: data.location,
      latitude: data.latitude,
      longitude: data.longitude,
      status: data.status,
      assigned_to: data.assigned_to,
      created: data.created_at
    });

  } catch (err) {
    console.error("Tracking API error:", err);

    return res.status(500).json({
      error: "Server error"
    });
  }
});

// =========================
// ADMIN LOGIN
// =========================

app.post("/api/admin/login", (req, res) => {
  const pin = String(req.body.pin || "");

  if (pin !== ADMIN_PIN) {
    return res.status(401).json({
      error: "Wrong PIN"
    });
  }

  const token = crypto
    .randomBytes(32)
    .toString("hex");

  sessions.set(token, true);

  return res.json({
    token
  });
});

// =========================
// ADMIN LOGOUT
// =========================

app.post("/api/admin/logout", auth, (req, res) => {
  const token = (
    req.headers.authorization || ""
  ).replace("Bearer ", "");

  sessions.delete(token);

  return res.json({
    ok: true
  });
});

// =========================
// ADMIN - GET COMPLAINTS
// =========================

app.get("/api/admin/complaints", auth, async (req, res) => {
  try {
    const { data, error } = await supabase
      .from("complaints")
      .select(
        "complaint_id,name,phone,category,description,location,latitude,longitude,status,assigned_to,created_at"
      )
      .order("created_at", {
        ascending: false
      });

    if (error) {
      console.error(
        "Admin complaints error:",
        error.message
      );

      return res.status(500).json({
        error: "Could not load complaints"
      });
    }

    const complaints = (data || []).map(c => ({
      id: c.complaint_id,
      name: c.name,
      phone: c.phone,
      category: c.category,
      description: c.description,
      area: c.location,
      location: c.location,
      latitude: c.latitude,
      longitude: c.longitude,
      status: c.status,
      assigned_to: c.assigned_to,
      created: c.created_at
    }));

    return res.json(complaints);

  } catch (err) {
    console.error("Admin API error:", err);

    return res.status(500).json({
      error: "Server error"
    });
  }
});

// =========================
// ADMIN - CHANGE STATUS
// =========================

app.patch(
  "/api/admin/complaints/:id",
  auth,
  async (req, res) => {
    try {
      const allowed = [
        "Submitted",
        "Under Review",
        "Assigned",
        "In Progress",
        "Resolved"
      ];

      const status = String(
        req.body.status || ""
      );
      const assigned_to = String(
    req.body.assigned_to || ""
).trim();


      if (!allowed.includes(status)) {
        return res.status(400).json({
          error: "Invalid status"
        });
      }

      const complaintId = String(
        req.params.id || ""
      )
        .trim()
        .toUpperCase();

      const { data, error } = await supabase
        .from("complaints")
        .update({
    status,
    assigned_to
})
        .eq("complaint_id", complaintId)
        .select(
          "complaint_id,name,phone,category,description,location,latitude,longitude,status,assigned_to,created_at"
        )
        .maybeSingle();

      if (error) {
        console.error(
          "Status update failed:",
          error.message
        );

        return res.status(500).json({
          error: "Status update failed"
        });
      }

      if (!data) {
        return res.status(404).json({
          error: "Complaint not found"
        });
      }

      return res.json({
        id: data.complaint_id,
        name: data.name,
        phone: data.phone,
        category: data.category,
        description: data.description,
        area: data.location,
        location: data.location,
        latitude: data.latitude,
        longitude: data.longitude,
        status: data.status,
        assigned_to: data.assigned_to,
        created: data.created_at
      });

    } catch (err) {
      console.error(
        "Status API error:",
        err
      );

      return res.status(500).json({
        error: "Server error"
      });
    }
  }
);

// =========================
// SUPABASE CONNECTION TEST
// =========================

async function testSupabase() {
  try {
    const { error } = await supabase
      .from("complaints")
      .select("id")
      .limit(1);

    if (error) {
      console.error(
        "Supabase connection failed:",
        error.message
      );
    } else {
      console.log(
        "Supabase connected successfully!"
      );
    }
  } catch (err) {
    console.error(
      "Supabase connection failed:",
      err.message
    );
  }
}

// =========================
// FRONTEND
// =========================

app.get("*", (req, res) => {
  res.sendFile(
    path.join(
      __dirname,
      "public",
      "index.html"
    )
  );
});

// =========================
// START SERVER
// =========================

app.listen(PORT, () => {
  console.log(
    `CivicConnect running on http://localhost:${PORT}`
  );
});

testSupabase();